name: Build and Test

on:
  push:

jobs:
  build:
    name: Build Job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: |
          echo "Building the project..."
          echo $GITHUB_REF
          # Add your build commands here

      - name: Run Tests
        run: |
          echo "Running tests..."
          # Add your test commands here
