name: Main Branch Protection

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  workflow_dispatch:

jobs:
  build_new:
    name: Build Job2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Build
        run: |
          echo "Building the project..."
          cat main.py
          cat service2.py
          echo "The ref is ${{ github.event }}"
          # Add your build commands here

      - name: Run Tests
        run: |
          echo "Running tests..."
          # Add your test commands here


# Option1: An action when the PR is merged to master to query all the labels 

# Option2: Service account to approve the PR, everytime a pr is merged to master
