name: Main Branch Protection

on:
  push:

jobs:
  build_new:
    name: Build Job2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: |
          echo "Building the project..."
          cat main.py
          cat service.py
          # Add your build commands here

      - name: Run Tests
        run: |
          echo "Running tests..."
          # Add your test commands here
