name: Main Branch Protection

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  pull_request:
    types:
      - closed

jobs:
  build_new:
    name: Build Job2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Build
        run: |
          echo "Building the project..."
          cat main.py
          cat service2.py
          # Add your build commands here

      - name: Run Tests
        run: |
          echo "Running tests..."
          # Add your test commands here
