name: Use GitHub App
on:
  workflow_dispatch:
  
  push:
    paths:
    - .github/workflows/use-github-app.yml

jobs:
  checkout-other-repo:
    runs-on: ubuntu-latest
    steps:
    - name: Get Token
      id: get_workflow_token
      uses: peter-murray/workflow-application-token-action@v2
      with:
        application_id: ${{ vars.GH_APPLICATION_ID }}
        application_private_key: ${{ secrets.GH_APPLICATION_KEY }}
    - name: show token
      id: show_token
      run: |
        echo ${{ steps.get_workflow_token.outputs.token }}
        curl -L -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ steps.get_workflow_token.outputs.token }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/mocio09/test-repo/installation -d '{"title":"Found a bug","body":"I'\''m having a problem with this.","assignees":["octocat"],"milestone":1,"labels":["bug"]}'
